### ISSUE TITLE
Erreur Detected blocking call to open 

### ISSUE THREAD

**Issue by ElGatitaux** [Matthyeux/train-traveler#13]
Bonjour,
L'erreur suivante apparait dans les logs. Je ne sais pas trop quoi faire.

Merci !

Enregistreur: homeassistant.util.loop
Source: util/loop.py:136
S'est produit pour la première fois: 18:20:11 (1 occurrences)
Dernier enregistrement: 18:20:11

Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'train_traveler' at custom_components/train_traveler/coordinator.py, line 83: self._timezone = pytz.timezone("Europe/Paris") (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/Matthyeux/train-traveler/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/train_traveler/__init__.py", line 31, in async_setup_entry next_journey_coordinator = JourneyCoordinator(connection, hass, entry) File "/config/custom_components/train_traveler/coordinator.py", line 83, in __init__ self._timezone = pytz.timezone("Europe/Paris")

**Comment by alainvdu69** [comment]
Bonjour,
idem 
2024-10-29 17:47:05.410 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'train_traveler' at custom_components/train_traveler/coordinator.py, line 83: self._timezone = pytz.timezone("Europe/Paris") (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/Matthyeux/train-traveler/issues
